name: Feature Request
description: Request a new feature
labels: ["Type: enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your feedback on ways Apache Arrow can be improved!
  - type: textarea
    id: description
    attributes:
      label: Describe the feature requested.
    validations:
      required: true
  - type: checkboxes
    id: component
    attributes:
      label: Component
      description: Which component does the feature most apply to?
      options:
        - label: Archery
        - label: Benchmarking
        - label: C
        - label: C#
        - label: C++
        - label: C++ - Gandiva
        - label: C++ - Plasma
        - label: Compute IR
        - label: Continuous Integration
        - label: Dart
        - label: Developer Tools
        - label: Documentation
        - label: FlightRPC
        - label: Format
        - label: GLib
        - label: Go
        - label: GPU
        - label: Integration
        - label: Java
        - label: JavaScript
        - label: Julia
        - label: MATLAB
        - label: Packaging
        - label: Parquet
        - label: Python
        - label: R
        - label: Ruby
        - label: Rust
        - label: Rust - Ballista
        - label: Rust - DataFusion
        - label: SQL
        - label: Swift
        - label: Website
        - label: Wiki
        - label: Other
    validations:
      required: true
